<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pNZEz6b' shared service.

return $this->privates['.service_locator.pNZEz6b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PrestataireController::adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemeController::addprest' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemeController::addsys' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PrestataireController:adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemeController:addprest' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemeController:addsys' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\PrestataireController::adduser' => '?',
    'App\\Controller\\SystemeController::addprest' => '?',
    'App\\Controller\\SystemeController::addsys' => '?',
    'App\\Controller\\PrestataireController:adduser' => '?',
    'App\\Controller\\SystemeController:addprest' => '?',
    'App\\Controller\\SystemeController:addsys' => '?',
]);
