<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7n7BLCc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7n7BLCc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7n7BLCc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7n7BLCc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7n7BLCc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7n7BLCc',
    'container.build_id' => '71fb95cc',
    'container.build_time' => 1565005128,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7n7BLCc');
