<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEExzqTd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEExzqTd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEExzqTd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEExzqTd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEExzqTd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EExzqTd',
    'container.build_id' => '058ad383',
    'container.build_time' => 1565001025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEExzqTd');
